### ISSUE TITLE
Goroutine errors from ServerMetricsCollector after update to v1.2.0

### ISSUE THREAD

**Issue by theoriginalgri** [promhippie/hcloud_exporter#70]
After updating to v1.2.0, goroutine errors are appearing:

Related PR #67.

```
level=info ts=2022-05-11T14:19:07.974591389Z msg="Launching HetznerCloud Exporter" version=502d4e3 revision=502d4e3 date=20220511 go=go1.17.8
level=info ts=2022-05-11T14:19:07.975042012Z msg="Starting metrics server" addr=0.0.0.0:9501
level=info ts=2022-05-11T14:19:07.975476253Z msg="TLS is disabled." http2=false
panic: send on closed channel

goroutine 1415 [running]:
github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect.func1(0xc0002d87e0, {0xae3340, 0xc0005b2d20}, 0xc0000397a0)
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:276 +0xcc5
created by github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:180 +0x485
level=info ts=2022-05-11T14:58:00.893971939Z msg="Launching HetznerCloud Exporter" version=502d4e3 revision=502d4e3 date=20220511 go=go1.17.8
level=info ts=2022-05-11T14:58:00.894436292Z msg="Starting metrics server" addr=0.0.0.0:9501
level=info ts=2022-05-11T14:58:00.894809455Z msg="TLS is disabled." http2=false
panic: send on closed channel

goroutine 136 [running]:
github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect.func1(0xc000290870, {0xae3340, 0xc0003cef00}, 0x0)
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:234 +0x9a5
created by github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:180 +0x485
level=info ts=2022-05-11T15:00:00.927846708Z msg="Launching HetznerCloud Exporter" version=502d4e3 revision=502d4e3 date=20220511 go=go1.17.8
level=info ts=2022-05-11T15:00:00.928540184Z msg="Starting metrics server" addr=0.0.0.0:9501
level=info ts=2022-05-11T15:00:00.930712455Z msg="TLS is disabled." http2=false
panic: send on closed channel

goroutine 377 [running]:
github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect.func1(0xc0001bc990, {0xae3340, 0xc000418180}, 0xc000038fa0)
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:269 +0xc45
created by github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect
	/home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:180 +0x485
level=info ts=2022-05-11T15:09:00.835010231Z msg="Launching HetznerCloud Exporter" version=502d4e3 revision=502d4e3 date=20220511 go=go1.17.8
level=info ts=2022-05-11T15:09:00.837048299Z msg="Starting metrics server" addr=0.0.0.0:9501
level=info ts=2022-05-11T15:09:00.839479696Z msg="TLS is disabled." http2=false
```

**Comment by tboerger** [comment]
@theoriginalgri I hope v1.2.1 finally also fixes the issue for you :)

**Comment by theoriginalgri** [comment]
Runs more stable now, thanks!

**Comment by tboerger** [comment]
I just tagged v1.2.2, it should be built in a few minutes. Please give it a try, maybe also test to enable the server metrics which have been disabled by default.
