### ISSUE TITLE
Bug: index out of range in server metrics

### ISSUE THREAD

**Issue by JanKoppe** [promhippie/hcloud_exporter#72]
I'm so sorry. Apparently the code is not really robust. Sometimes there seem to be no metrics datapoints being returned from the API (did not encounter that while testing).

Will supply a fix for this.

```
{"date":"20220511","go":"go1.17.8","level":"info","msg":"Launching HetznerCloud Exporter","revision":"2840dbb","ts":"2022-05-12T05:51:48.892510824Z","version":"1.2.1"}
{"addr":"0.0.0.0:9501","level":"info","msg":"Starting metrics server","ts":"2022-05-12T05:51:48.892659373Z"}
{"http2":false,"level":"info","msg":"TLS is disabled.","ts":"2022-05-12T05:51:48.892772565Z"}
panic: runtime error: index out of range [0] with length 0

goroutine 523 [running]:
github.com/promhippie/hcloud_exporter/pkg/exporter.(*ServerMetricsCollector).Collect(0xc000254750, 0xc0005c3760)
        /home/runner/work/hcloud_exporter/hcloud_exporter/pkg/exporter/server_metrics.go:204 +0x1265
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446 +0x102
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:538 +0xb4d
```

**Comment by tboerger** [comment]
Same for me, I also have not been able to run into the other issue. Shit happens :)

**Comment by theoriginalgri** [comment]
Could the reason for this be that you're checking for metrics of `now` (start and end) and the actual server might be a second in front of the hetzner api?

**Comment by tboerger** [comment]
The same approach is already used for the load balancer metrics without issues.

**Comment by tboerger** [comment]
I just tagged v1.2.2, it should be built in a few minutes. Please give it a try, maybe also test to enable the server metrics which have been disabled by default.
